config/routes.rb
Aramiske::Application.routes.draw do  
  
  resources :contacts

  resources :portfolios

  get "blog/index"
  
  resources :posts

  

  resources :services

  match 'home' => 'home#index'
  
  root :to => 'home#index'

end

app/models/blog.rb
class Blog
  
  require 'active_model'

  attr_writer :post_source
  
  def initialize
    @entries = []
  end
  
  def entries
    @entries.sort_by{ |e|  e.pubdate}.reverse.take(10)
  end
  
  def add_entry(entry)
    @entries << entry
  end
  
  def new_post(*args)
    post_source.call(*args).tap do |p|
      p.blog = self
    end
  end

  def title
    "Watching Paint Dry"
  end
  
  def subtitle
    "The trusted source for drying paint news & opinion"
  end
  
  private 
  
  def post_source
    @post_source ||= Post.public_method(:new)
    
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  
end

app/models/post.rb
require 'active_model'

class Post
  

  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations 
  
  validates :title, presence: true
  
  attr_accessor :blog, :title, :body, :image_url, :pubdate
  
  def initialize(attrs={})
    attrs.each do |k,v| send("#{k }=",v) end
  end
  
  def persisted?
    false  
  end
  
  def picture? 
    image_url.present?
  end
    
  def publish(clock=DateTime)
    return false unless valid?
    self.pubdate = clock.now
    @blog.add_entry(self)
  end

  
end

app/models/service.rb
class Service < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper :exhibits
  
  before_filter :init_blog
  
  private
  def init_blog
    @blog = THE_BLOG
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index

  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
    
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @post = @blog.new_post
  end
  
  def create
    @post = @blog.new_post(params[:post])   
    if  @post.publish
      redirect_to root_path, notice: "Post added!"
    else
       flash[:error] = 'A title might be a good start'
      render "new", notice: "Post not added!"
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
  def exhibit(model, context)
      # Doing a string comparison because of Rails class-reloading weirdness
    case model.class.name 
    when 'Post'
      if model.picture? 
        PicturePostExhibit.new(model, context)
      else
        TextPostExhibit.new(model, context) 
      end
    else
        model
    end 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/blog/_entry.html.erb
<% entry = exhibit(entry, self) %> 
  <p><time pubdate="pubdate"><%= entry.pubdate %></time></p>
  <h3><%=entry.title %></h3>
<%= entry.render_body %> 

app/views/blog/index.html.erb
<div class="sidebar two columns">
  <nav> 
    <ul>
      <li><%= link_to "New post...", new_post_path %></li> 
    </ul>
  </nav>
</div>


<section id="content" class="container clearfix">
	<header class="page-header">
		<h1 class="page-title">Welcome to our blog</h1>
	</header><!-- end .page-header -->
	<section id="main">
		<article class="entry single clearfix">
			<div class="entry-body">
				<h1 class="title"><%= @blog.title %></h1>
				<p><%= @blog.subtitle %></p>
				<%= render partial: "entry", collection: @blog.entries %>
			</div>
		</article>
	</section>
</section>

app/views/home/index.html.erb
  </br>  </br>  </br>  </br>  </br>  </br>  </br>  </br>  </br>  </br>  </br>  </br>  </br>  </br>  </br>
	
</section><!-- end #content -->

<footer id="footer" class="clearfix">

	<div class="container">

		<div class="three-fourth">

			<nav id="footer-nav" class="clearfix">

				<ul>
          <li><%=link_to "Home", home_path %></li>         
          <li><%=link_to "Services", services_path %></li>  
          <li><%=link_to "Blog", services_path %></li>                              
          <li><%=link_to "Portfolio", portfolios_path %></li>                                        
          <li><%=link_to "Contact", contacts_path %></li>                                                  
				</ul>
				
			</nav><!-- end #footer-nav -->

			<ul class="contact-info">
				<li class="address">443 Mt Glorious Road, Samford Valley, 4520, Australia</li>
				<li class="phone">(0411) 815-602</li>
				<li class="email"><a href="mailto:mmochan@aramiske.com.au">mmochan@aramiske.com.au</a></li>
			</ul><!-- end .contact-info -->
			
		</div><!-- end .three-fourth -->

		<div class="one-fourth last">

			<span class="title">Stay connected</span>

			<ul class="social-links">
				<li class="twitter"><a href=https://twitter.com/#!/aramiske1>Twitter</a></li>
				<li class="facebook"><a href="#">Facebook</a></li>
				<li class="digg"><a href="#">Digg</a></li>
				<li class="vimeo"><a href="#">Vimeo</a></li>
				<li class="youtube"><a href="#">YouTube</a></li>
				<li class="skype"><a href="#">Skype</a></li>
			</ul><!-- end .social-links -->

		</div><!-- end .one-fourth.last -->
		
	</div><!-- end .container -->

</footer><!-- end #footer -->

<footer id="footer-bottom" class="clearfix">

	<div class="container">

		<ul>
			<li>Aramiske &copy; 2012</li>
			<li><a href="#">Legal Notice</a></li>
			<li><a href="#">Terms</a></li>
		</ul>

	</div><!-- end .container -->

</footer><!-- end #footer-bottom -->
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aramiske</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "http://maps.google.com/maps/api/js?sensor=false" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
  <header id="header" class="container clearfix">
  	<%=image_tag("logo.png") %>
  	<nav id="main-nav">	
  		<ul>
  			<li class="current">
          <%= link_to "Home", home_path, 'data-description' => 'All starts here' %>
  				<ul>
  					<li><a href="logos-slider.html">Logos Slider</a></li>
  					<li><a href="photos-slider.html">Photos Slider</a></li>
  				</ul>
  			</li>
  			<li>
				<%= link_to "Services", services_path, 'data-description' => 'All the different stuff' %>
  				<ul>
  					<li><a href="about-us.html">About Us</a></li>
  					<li><a href="our-team.html">Our Team</a>
  						<ul>
  							<li><a href="we-are-hiring.html">We are hiring</a></li>
  						</ul>
  					</li>
  					<li><a href="elements.html">Elements</a></li>
  					<li><a href="pricing-tables.html">Pricing Tables</a></li>
  					<li><a href="columns.html">Columns</a></li>
  					<li><a href="#">Third Level Item</a>
  						<ul>
  							<li><a href="#">This is a simple example</a></li>
  							<li><a href="#">Of the third level</a></li>
  							<li><a href="#">Navigation item</a></li> 
  						</ul>
  					</li>
  				</ul>
  			</li>
  			<li>
          <%= link_to "Blog", blog_index_path, 'data-description' => 'What we think' %>        
  				<ul>
  					<li><a href="single-post.html">Single Post</a></li>
  				</ul>
  			</li>
  			<li>
				<%= link_to "Portfolio", portfolios_path, 'data-description' => 'Work we are proud of' %>        
  				<ul>
  					<li><a href="portfolio-2-columns.html">2 Columns</a></li>
  					<li><a href="portfolio-3-columns.html">3 Columns</a></li>
  					<li><a href="portfolio-4-columns.html">4 Columns</a></li>
  					<li><a href="single-project.html">Single Project</a></li>
  				</ul>
  			</li>
  			<li>
				<%= link_to "Contact", contacts_path, 'data-description' => 'Enquire here' %>                
  			</li>
  		</ul>
  	</nav><!-- end #main-nav -->
	
  </header><!-- end #header -->
	

<%= yield %>

</body>
</html>

app/views/posts/_picture_body.html.erb
<figure>
	<img src="<%= post.image_url %>"/> 
	<figcaption><%= post.body %></figcaption>
<figure/>

app/views/posts/_text_body.html.erb
<figure>
	<figcaption><%= post.body %></figcaption>
<figure/>

app/views/posts/new.html.erb
<section id="content" class="container clearfix">
	<header class="page-header">
		<% if flash[:error]%>
			<div class=error><%= flash[:error] %></div>
		<% end %>	
		<br />
		<h1 class="page-title">Write something interesting....</h1>
	</header>
	<section id="main">
		<article class="entry single clearfix">
			<div class="entry-body">
				<%= form_for @post do |f| %>
				  <h1 class="title"><%= f.text_field :title %> </h1>
				  <%= f.text_area :body %> 
				  <%= label :image_url, "Picture URL:" %> 
				  <%= f.text_field :image_url %>  
				  <%= f.submit %>
				<% end %>
			</div>	
		</article>
	</section>
</section>
    